### PR TITLE
Support Tigrinya and Simplified Chinese in PDF export

### PR DESCRIPTION
**Pull request by MizukiTemma**
### Short description

This PR adds font and settings for PDF export in Tigrinya and Simplified Chinese

### Proposed changes

- Add new font data for Simplified Chinese
- Add the slug "ti" in the settings for Geʽez font (Tigrinya is written in Ge'es characters like Amharic, so far as I googled)

### Side effects

- Sentences are going too far on the right side of each page in the exported PDF in Simplified Chinese. I guess this is an upstream issue, though feel free to suggest if you have a idea for (quick local) fix 😺 

### Resolved issues

Fixes: (partially) #2870 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by JoeyStk** [comment]
For Chinese:
I translated "Deutsch selber lernen" to Chinese and then generated a PDF for it. On the right side of the PDF there is a bit of an overhang (screenshot below)

grafik

**Review by JoeyStk — APPROVED** [review]
Except for my comment about the overhang, I think this is good to go! :rocket:

**Comment by lunars97** [comment]
maybe it is possible to add `overflow-wrap: break-word` :thinking: Everything works fine except this overflow. In LibraOffice it is showing that the sentence is way out of the border
image

**Comment by MizukiTemma** [comment]
@JoeyStk @lunars97 
Stupid me 🙈 I only had to check xhtml2pdf repository more 🙈 There was already a discussion about this overflow problem and even a solution `-pdf-word-wrap: CJK;` 😅 

Could you review this PR again? Not only Simplified Chinese and Tigrinya, but also no side effect to other languages?

**Review by lunars97 — APPROVED** [review]
Good catch with the word-wrap, it looks good now! :heart_eyes_cat:

**Review by JoeyStk — APPROVED** [review]
Nice, works well! Thank you very much :)

**Pull request merged**
