### PR TITLE
Release `2024.8.1`

### PR DESCRIPTION
**Pull request by MizukiTemma**
# Release notes

- [ [#2903](https://github.com/digitalfabrik/integreat-cms/issues/2903) ] Refactor collection of pagetranslation over/under hix threshold
- [ [#2917](https://github.com/digitalfabrik/integreat-cms/issues/2917) ] Fix hix for pages without text
- [ [#2918](https://github.com/digitalfabrik/integreat-cms/issues/2918) ] Fix jumping language tabs
- [ [#2973](https://github.com/digitalfabrik/integreat-cms/issues/2929) ] Fix error at creating POI in event form
- [ [#2922](https://github.com/digitalfabrik/integreat-cms/issues/2922) ] Use always "Veranstaltung" as translation of "event"

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by JoeyStk** [comment]
Does someone else also get an `Integrity Error` when create a new organization?

**Comment by MizukiTemma** [comment]
> Does someone else also get an `Integrity Error` when create a new organization? (Can't reproduce it on the test server (yet))

Sadly me neither 😿 Where was it reported?

**Comment by JoeyStk** [comment]
> Sadly me neither 😿 Where was it reported?

I'm the one getting it, but as no one else seems to have this problem, it's probably something on my side

**Review by JoeyStk — APPROVED** [review]
Except the one bug only I seem to have, everything seemed to work!

**Pull request merged**
