### PR TITLE
Ignore soft hyphens when detecting links

### PR DESCRIPTION
**Pull request by PeterNerlich**
### Short description

Ignore soft hyphens when auto detecting links in TinyMCE

### Proposed changes

- Ignore soft hyphens in detection only, but don't strip them out of the text content.

### Side effects

- Nonsensically placed soft hyphens will not be removed from the page. But on the flip side, sensibly placed ones will also stay.

### Resolved issues

Fixes: #2998

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by JoeyStk — DISMISSED** [review]
Thank you very much!
I couldn't reproduce any of the reported issues, but as I understand it, this should be a good attempt at solving them :)

**Comment by PeterNerlich** [comment]
> I couldn't reproduce any of the reported issues

Do you mean the original issue or what I mentioned under *Side effects*?

**Comment by JoeyStk** [comment]
> Do you mean the original issue or what I mentioned under Side effects?

The original reported issue

**Comment by PeterNerlich** [comment]
@JoeyStk did you use the *Steps to reproduce* from #2998?

**Review by deen13 — APPROVED** [review]
I was able to reproduce the issue and confirm that this pull request resolves it. The fix works as expected. 👍

**Review by MizukiTemma — APPROVED** [review]
I could reproduce the reported problem and this PR seems to have fixed it 🎉  

Thank you so much for your research, analysis and implementation 🥹 🙏

**Pull request merged**
