### PR TITLE
Release `2022.8.0`

### PR DESCRIPTION
**Pull request by svenseeberg**
### Resolved issues

* [ [#1390](https://github.com/digitalfabrik/integreat-cms/issues/1390) ] Move files via drag and drop
* [ [#1606](https://github.com/digitalfabrik/integreat-cms/issues/1606) ] Remove warning at POI contacts
* [ [#1571](https://github.com/digitalfabrik/integreat-cms/issues/1571) ] Show offline downloads in statistics
* [ [#1464](https://github.com/digitalfabrik/integreat-cms/issues/1464) ] Fix status of translation with only minor public version
* [ [#1623](https://github.com/digitalfabrik/integreat-cms/issues/1623) ] Fix imprint publish/update button
* [ [#1534](https://github.com/digitalfabrik/integreat-cms/issues/1534) ] Invalidate cache after moving nodes

### CODE REVIEW

**Comment by svenseeberg** [comment]
Blocked by https://github.com/digitalfabrik/integreat-cms/issues/1622

**Review by timoludwig — DISMISSED** [review]
I guess this is now ready to be released 🚀

**Comment by david-venhoff** [comment]
It looks like the Changelog did somehow get corrupted...
The entry for #1535 should be in the unreleased section. I am not quite sure how that happened, since it was in the correct section in the pr.

**Comment by timoludwig** [comment]
> I am not quite sure how that happened, since it was in the correct section in the pr.

Git just works with simple patch files under the hood, and for patch files, the lines before and after the changed line are decisive about where the changed line ends up in the final file. The changelog patch for your PR was:
```
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 65476dae..9ae3ef2c 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -10,6 +10,7 @@ UNRELEASED
 * [ [#1585](https://github.com/digitalfabrik/integreat-cms/issues/1585) ] Hide news after 28 days
 * [ [#1600](https://github.com/digitalfabrik/integreat-cms/issues/1600) ] Improve XLIFF export bulk option description
 * [ [#1511](https://github.com/digitalfabrik/integreat-cms/issues/1511) ] Fix PDF generation for long filenames
+* [ [#1535](https://github.com/digitalfabrik/integreat-cms/issues/1535) ] Fix event api performance


 2022.6.3
```

Since the three lines above and below above were still identical (and just the heading changed from "UNRELEASED" to "2022.7.0", it thought "well, good enough for me, I'm sure enough to not make a merge conflict out of this patch, I will just apply it anyways even though other parts of the file changed"...

**Review by timoludwig — APPROVED** [review]

**Pull request merged**
