### PR TITLE
Catch and handle errors of FCM

### PR DESCRIPTION
**Pull request by MizukiTemma**
### Short description

This PR add an error handling for invalid FCM URL.

**update**
This takes care of timeout exception too. I've totally forgotten that those two issues are related each other.

### Proposed changes

- Catch errors and show an error message to users 
- The error message is left universal (not specific to any error type) because many types are possible. 

### Side effects

- The rendering after failing of a push notification is partially broken. 
- A question regarding this rendering: don't we want to redirect not no the create view but to the edit view becuase the push notification is saved in this case?
- I'll suggest to fix the rendering in a separate PR/issue.

### Resolved issues

Fixes: #2025 , #2790 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by david-venhoff — CHANGES_REQUESTED** [review]
Thanks, this fixes both linked issues. 
I think, as part of the clean code initiative, we should avoid introducing new `pylint: disable=` comments. Maybe one option would be to handle  the errors directly at `self.send_pn`

**Comment by MizukiTemma** [comment]
@david-venhoff 
That's a nice idea 😸 Applied!

**Review by david-venhoff — APPROVED** [review]
Nice :)

**Review by ulliholtgrave — APPROVED** [review]
Thanks for adding this extra handling :+1:

**Pull request merged**
