### PR TITLE
Fix pylint useless suppression warnings

### PR DESCRIPTION
**Pull request by charludo**
### Short description

Fix pylint useless suppression warnings

### Proposed changes

- remove the useless suppressions

### Side effects

- none

### Resolved issues

Fixes: n/a

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by timoludwig — APPROVED** [review]
Thanks!
Is there any possibility to make the pylint job fail when this warning is thrown? Otherwise we will probably re-introduce similar useless suppression statements in the future...

**Comment by charludo** [comment]
> he `enable` to enable the warning and `fail-on` to set the return code

tried that as well, same result. Using only `fail-on` was more of a sanity check to see if pylint even recognized the setting

> > Good idea! It _should_ be possible, see: [pylint-dev/pylint#4398](https://github.com/pylint-dev/pylint/pull/4398), and changing `enable` to `fail-on` in `pyproject.toml` still keeps the warnings, but the exit code in both cases is `0`.
> 
> I think it's not an either/or, but it needs both statements... the `enable` to enable the warning and `fail-on` to set the return code... Also, I think the `fail-on` needs to be in the `[tool.pylint.main]` section?
> 
> Just setting
> 
> ```
> fail-on = [
>     "all"
> ]
> ```
> 
> might work as well?

Good idea, I'll have a try...

**Comment by charludo** [comment]
> > he `enable` to enable the warning and `fail-on` to set the return code
> 
> tried that as well, same result. Using only `fail-on` was more of a sanity check to see if pylint even recognized the setting
> 
> > Just setting
> > ```
> > fail-on = [
> >     "all"
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > might work as well?
> 
> Good idea, I'll have a try...

No luck, unfortunately

**Review by MizukiTemma — APPROVED** [review]
✅ thank you 🙂

**Comment by timoludwig** [comment]
> If it's alright with you, I'll merge as-is, without squashing, since the commits are all about different "issues"

I agree :+1:

**Pull request merged**
