### PR TITLE
Update firebase cloud messaging to v1

### PR DESCRIPTION
**Pull request by david-venhoff**
### Short description

This pr updates the firebase push notification api from legacy to v1.

To test that this pr works you can follow these steps:
1. Get credentials from passbolt, you might need to request permission for that file 
2. Store the credentials.json file on your computer and set the `FCM_CREDENTIALS` accordingly
3. In `firebase_api_client.py` set `validate_only` to False, so that messages can be sent
4. Open Testumgebung in the mobile app (Hidden regions can be selected if you type `wirschaffendas` in the search box)
5. Run the server, navigate to Testumgebung and send a new push notification. Make sure that the push notification only gets sent to Testumgebung, otherwise users will see the test message!

I added the label `prio: high` because the api we currently use will be removed in june, and we need to have published a release with support for the newer api by then

### Proposed changes

- Update the POST payload format
- Update the authentification method and add a dependency on `google.auth` for that
- Fix the behavior in debug mode: Only use the testregion and per default don't actually send the messages
- Update the tests

### Side effects

Ideally everything should work as before 

### Resolved issues

Fixes: #1853 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by svenseeberg** [comment]
The Integreat CMS config is prepared: https://git.tuerantuer.org/DF/salt/commit/faf95965ab6dfff83c54880bd0be057d096d937e

**Review by deen13 — APPROVED** [review]
Tested on my iOS device and it worked perfectly! 👍 

Please remember that if your device is set to English language, you'll need to publish English news to receive notifications. 😬

**Comment by charludo** [comment]
@david-venhoff I'm getting an error from firebase `Firebase Cloud Messaging API has not been used in project [12-digit number here] before or it is disabled.`

Have I missed a step somewhere? The credentials file is being loaded correctly, as far as I can tell, although I am not 100% sure it's the *correct*  credentials.json file 😄

**Comment by david-venhoff** [comment]
We currently have two credential files, one for google translate and one for fcm. The correct one should be titled `Integreat FCM Service Account Credentials` in passbolt

**Comment by charludo** [comment]
> We currently have two credential files, one for google translate and one for fcm. The correct one should be titled `Integreat FCM Service Account Credentials` in passbolt

Oh, alright. Then I'm indeed using the wrong one. Can't seem to find the other one though, how do I request access to it? 🙈

**Comment by david-venhoff** [comment]
Apparently I can give you access to that :smile: 
You should be able to see it now

**Comment by charludo** [comment]
> Apparently I can give you access to that 😄 You should be able to see it now

Yes, nice, thank you!

**Review by charludo — APPROVED** [review]
Very nice! Everything seems to work 😄

**Pull request merged**
