### PR TITLE
Improve spacing in page form, poi form and event form for mobile view

### PR DESCRIPTION
**Pull request by JoeyStk**
### Short description
This PR improves spacings in the page form, poi form and event.

### Proposed changes
- Add 0.75rem margin top to the first box
- Remove the gap-2 so everywhere is the same margin (0.75rem)

### Side effects

There might be some once #2039 is pushed

### Resolved issues

Fixes: #2040 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by charludo — APPROVED** [review]
LGTM, a lot cleaner on very small screens

**Review by timoludwig — CHANGES_REQUESTED** [review]
Ah that was the reason for these classes... thanks for figuring that out and sorry for removing them :innocent: 

Could you resolve the conflicts, then I guess this is ready to go.

**Comment by JoeyStk** [comment]
Yes, will do. Do I also need a changelog for this or are these changes too minor?

**Comment by timoludwig** [comment]
> Yes, will do. Do I also need a changelog for this or are these changes too minor?

For once, it minor, and also it's not an improvement in comparison to the last version, because this bug was a side effect of the all unreleased changes.

**Review by timoludwig — APPROVED** [review]

**Pull request merged**
