### PR TITLE
Show test banner in test systems

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

With the increasing number of test & production systems of our different whitelabel solutions, I think this banner helps to keep the overview.

### Proposed changes

- Show test banner in test systems

### Resolved issues

Fixes: #1547

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by PeterNerlich** [comment]
Would it make sense to add a banner to the management commands on this occasion as well?

**Comment by timoludwig** [comment]
> Would it make sense to add a banner to the management commands on this occasion as well?

No, since management commands are invoked via the shell, the admin needs to explicitly type the server they want to connect to, and also most shells show the host name on every prompt anyway, so if you see
```
timo@integreat-test ~ % integreat-cms-cli migrate
```
it's pretty obvious that the command only affects the `integreat-test` server.

**Review by ulliholtgrave — APPROVED** [review]
Thanks. Probably a good change/idea even though it kinda seems strange that we even need this :sweat_smile:

**Review by PeterNerlich — APPROVED** [review]
:+1:

**Pull request merged**
