### PR TITLE
Release `2024.1.0`

### PR DESCRIPTION
**Pull request by ulliholtgrave**

### CODE REVIEW

**Comment by MizukiTemma** [comment]
Should we merge #2608 too?

**Review by MizukiTemma — DISMISSED** [review]
:tada:

**Comment by svenseeberg** [comment]
I guess we should not wait for https://github.com/digitalfabrik/integreat-cms/pull/2596

**Review by timobrembeck — APPROVED** [review]
:rocket:

**Review by seluianova — APPROVED** [review]

**Pull request merged**
