### PR TITLE
Extend select all checkbox to events and pois

### PR DESCRIPTION
**Pull request by JoeyStk**
### Short description

This PR extends the "select all" checkbox for translations to events and pois

### Proposed changes

- Add checkbox to events and pois

### Side effects

None?

### Resolved issues

Fixes: #3185

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by lunars97 — COMMENTED** [review]
Everything looks good :+1: 
But I have one question: Do we need it here as well? To uncheck, for example, all languages? 
image

**Comment by JoeyStk** [comment]
Yes. I think we need it there too. Where is this? Is this the imprint? :)

**Comment by lunars97** [comment]
> Yes. I think we need it there too. Where is this? Is this the imprint? :)

it is where you implemented, but after automatically translating them and checking it again you see there no option anymore to uncheck all of them...

**Comment by JoeyStk** [comment]
> It is where you implemented, but after automatically translating them and checking it again you see there no option anymore to uncheck all of them...

Ah, now I get it :) I don't know, this is probably a question for @osmers :)

**Comment by osmers** [comment]
What would be the use case in unchecking them all? When implementing it we decided to leave already translated languages checked bcs the assumption is, that if a translation exists, they will want to translate the changes as well, right?

**Comment by JoeyStk** [comment]
> What would be the use case in unchecking them all? When implementing it we decided to leave already translated languages checked bcs the assumption is, that if a translation exists, they will want to translate the changes as well, right?

Yes, I think you're right. I don't think we need to uncheck the languages in bulk then :)

**Review by MizukiTemma — APPROVED** [review]
Looks good 👍

**Pull request merged**
