### PR TITLE
Update tinymce to v7

### PR DESCRIPTION
**Pull request by david-venhoff**
### Short description

While working on #3082 I also attempted to update tinymce to v7. Since that turned out to be a lot of effort, I decided to open another pr for that.

### Proposed changes

- Update tinymce to v7

### Side effects

- Potentially a lot, I did not do much testing yet. Here are the migration guides: https://www.tiny.cloud/docs/tinymce/latest/migration-from-6x/ and https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/
- ~~The license of tinymce changed to GPL, could that potentially be a problem for us?~~ GPL is no problem for us

### Resolved issues

Fixes: #1274

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by ulliholtgrave — APPROVED** [review]
Thanks for your effort! (Suprisingly) I couldn't find any problems :+1:

**Review by MizukiTemma — APPROVED** [review]
Me neither found any bug :tada: 

Thank you so mucb :smile_cat:

**Comment by MizukiTemma** [comment]
@osmers 

TinyMCE will look a little bit diffrefent from the current appearance once this PR comes into force on the production system.

**Comment by osmers** [comment]
@MizukiTemma yep, I've been informed :) I think that should be ok, it does not seem too different

**Pull request merged**
