### PR TITLE
Add fax icon svg

### PR DESCRIPTION
**Pull request by ulliholtgrave**
### Short description

This PR adds the functionality to insert an icon for fax numbers to the editor.

### Proposed changes

- Add fax icon SVG.
- Update editor functions.

### Resolved issues

Fixes: #3225 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by david-venhoff — APPROVED** [review]
lgtm

**Review by MizukiTemma — APPROVED** [review]
Thank you :smile_cat:

**Comment by osmers** [comment]
@ulliholtgrave I assume you took the svg from flaticon and thus we have no issues with the copyright?

**Comment by ulliholtgrave** [comment]
@osmers yes, exactly

**Comment by juliankehne** [comment]
I found that the alt attribute is 'null' created an issue for it: #3237

**Pull request merged**
