### PR TITLE
Release `2023.9.1`

### PR DESCRIPTION
**Pull request by ulliholtgrave**
### Short description

Small improvements

### CODE REVIEW

**Review by timobrembeck — APPROVED** [review]
:rocket:

**Comment by svenseeberg** [comment]
Small but relevant improvements. Should we wait for another specific PR? Otherwise I'm absolutely voting for merging this now ;)

**Review by svenseeberg — DISMISSED** [review]

**Comment by timobrembeck** [comment]
If we want to, we can wait a few more minutes until #2426 is built (and merged and built again), but not too important I guess...

**Comment by svenseeberg** [comment]
> If we want to, we can wait a few more minutes until #2426 is built (and merged and built again), but not too important I guess...

We can easily wait for that. As long as the repair tree command can be used later today, I'm happy :)

**Review by timobrembeck — APPROVED** [review]

**Pull request merged**
