### PR TITLE
Show only unsaved warning when changes are not saved

### PR DESCRIPTION
**Pull request by MizukiTemma**
### Short description

This is the second try after the approach in #2132 stucked due to the behaviour of FireFox.

### Proposed changes

- Benefit from #2243 😁 

### Side effects

- I hope there is none.

### Resolved issues

Fixes: #2128 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by david-venhoff — CHANGES_REQUESTED** [review]
Unfortunately this still breaks the autosave functionality on firefox for me 🙈. 
However, there seems to be a method that might fix our problem: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon
Have we every tried that in the previous pr?

Apart from that, I think the `data-unsaved-warning-exclude` attribute should also be added to the `imprint_sbs` and the `page_sbs`.
Also, since the input events from tinymce forms are not required anymore, we can probably remove this in `tinymce-init.ts`:
```ts
                // When the editor becomes dirty, send an input event, so that the unsaved warning can be shown
                editor.on("dirty", () => {
                    if ((editor.targetElm as HTMLElement).hasAttribute("data-unsaved-warning-exclude")) {
                        return;
                    }
                    document.querySelectorAll("[data-unsaved-warning]").forEach((element) => {
                        element.dispatchEvent(new Event("input"));
                    });
                });
```

**Comment by MizukiTemma** [comment]
@david-venhoff
ohh stupid me 🙈 I hadn't checked it with FireFox before opening the PR 🙈 

With `navigator.sendBeacon` auto save is working, but there is one problem that it return only `true` or `false` and we cannot set `form.action` to the url returned by the server. Without `form.action = data.url` multiple of new pages will be generated if an user is editing a brand new page, and I don't come up with any alternative way to catch the server response than staying with `fetch` 😿

**Comment by david-venhoff** [comment]
Ahh okay. In that case we could maybe have two autosave implementations, one for normal timed autosaves and one for when the user is attempting to leave the page?
As far as I understand, we only have to update the form action when the user is not leaving the page, so in the problematic case we could use the beacon api.

**Comment by MizukiTemma** [comment]
I tried Firefox-oriented some improvement, but it still needs adjustment for cases when a page already exists and the first translation of a non-root language is being edited, and it seems also unstable now in other browsers than Firefox.

Honestly saying, I'm thinking whether it's worth this much of effort 😢 (or just I'm not good enough at this thema)

**Comment by MizukiTemma** [comment]
Same with #2132

**Pull request closed without merging**
