### PR TITLE
Actually fix notranslate ltr direction

### PR DESCRIPTION
**Pull request by PeterNerlich**
### Short description

We discovered that #2873 fixed only the in-editor representation on CMS side, not on the app side. This is because we employed CSS to do that, which only applied on CMS side. We currently don't have any CSS we serve to be injected wherever HTML is embedded on the app side.

### Proposed changes

- Make `notranslate` button and telephone numbers render `notranslate` spans with `dir="ltr"` attribute
- Add normalization to `clean_content()` for page translations to ensure all `notranslate` spans have
  - the `notranslate` class
  - the `translate="no"` attribute
  - the `dir="ltr"` attribute

### Side effects

- If we have rtl languages as source language in the future, this will need more complex logic to dynamically adjust and work the other way around
- We have to fix all currently online page translations once

### Resolved issues

Fixes: #2854

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by charludo — APPROVED** [review]
Looks good to me! 🎉 

From the discussion in MM I gathered that this does not fix the DeepL related bug though, right? Does it still make sense to merge?

**Comment by PeterNerlich** [comment]
> From the discussion in MM I gathered that this does not fix the DeepL related bug though, right?

I seems the DeepL bug with moving spans marked with `translate="no"` is entirely unrelated to and unaffected by the presence or absence of `dir="ltr"`

**Comment by JoeyStk** [comment]
>  Does it still make sense to merge?

I'm wondering about the same thing :)

**Comment by PeterNerlich** [comment]
I feel like there is some confusion about what this PR does and what problems exist outside of that, so I'll do a brain dump of my understanding.

- There is a rendering/layouting issue with multi-word content in `span`s marked with `translate="no"` wherever the source language is *left to right* but the target language is *right to left*.
  This is an oversight on our part and not an issue in browsers or anything, because the browser has no reason to care about `translate="no"`, it doesn't translate anything, this is just another `span` that gets rendered, and we told it that this language is *right to left* and all inline elements should be layouted that way.
    - This PR addresses this problem, telling the browser that these `span`s should always be layouted *left to right*.
- There is a bug in DeepL when translating HTML content. Elements can be marked with `translate="no"` to convey to DeepL that this content should be kept as is, but apparently sometimes the element gets put at the very start of the sentence or paragraph, not in a place that makes sense and retains the meaning.
  This appears to be different between languages and I suspect has to be trained into the translation models for every language separately, which leads me to expect that this will not be a "quick fix" for DeepL.
  <details><summary>Example</summary>
  
  image
  image
  
  </details>
  
    - This is *not* addressed by this PR and does not influence the effectiveness of this PR.
    
> Does it still make sense to merge?

So that's my impression of the situation, and if it is a sufficiently close approximation of reality, then **yes, it does make sense to merge**. However, in the process of the confusion and discussions on Mattermost we kind of established that there are larger problems with DeepL that likely won't be fixed that quickly and that we cannot do anything about ourselves.

**Review by JoeyStk — APPROVED** [review]
Thank you! LGTM!

**Pull request merged**
