### PR TITLE
Fix release notes number of #2137

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

It seems the new tool does not prevent all errors in the release notes...
Any suggestions how we could make sure that the correct number is referenced?
Maybe a check that each release note of a PR is also mentioned in the PR description?

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by JoeyStk — COMMENTED** [review]
First of all, thank you a lot for the quick fix again
The issue with the wrong issue number is fixed. I have a question about the new implementation for the release note script. I tried to create the release notes for #2133 (just for testing). However I received an error message (see below).
grafik
I also got this error message for the two other release notes I tried to create

**Comment by timoludwig** [comment]
@JoeyStk Ah good point, I forgot to add a check whether the dependency jq is installed (jq is a json parser for the command line).
I'll add one. In order to use the tool, you have to install `sudo apt-get install jq `.

**Review by JoeyStk — APPROVED** [review]
Yes, now it works! Thank you very much. 
And once again I'm sorry, this time for the wrong issue folder :see_no_evil: 
No more merges on a weekend for me

**Comment by timoludwig** [comment]
> And once again I'm sorry, this time for the wrong issue folder see_no_evil No more merges on a weekend for me

Haha, no problem, I mean we missed it in the review as well :wink:

**Review by ulliholtgrave — APPROVED** [review]
Thanks, seems to work as expected :+1:

**Pull request merged**
