### PR TITLE
Client side validation in event form

### PR DESCRIPTION
**Pull request by theresantonie**
### Short description
Enable client to validate the verification of required fields inside the event form.

### Proposed changes
-  Fixed missing removal of "required" attribute when selecting "all day" while a previous value is set for start_time or end_time input fields.
- Changed behaviour when input fields are un-hidden to display their previous values instead of empty fields.
- Added support for client side validation of conditionally required field recurrence_end_date.  

### Side effects
- None 

### Resolved issues

Fixes: #246

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by lunars97 — APPROVED** [review]
Thank you for your PR :green_heart: Looks good to me and works as expected!

**Review by david-venhoff — APPROVED** [review]
Thanks!
Could you add a changelog entry and squash the commits? Then this is good to go :rocket: 

On minor detail: In the description of the pr, you can link the closed issue using just its id, like this:
```
### Resolved issues


Fixes: #246
```

This has the advantage that github will automatically close the issue once the pr is merged.

**Comment by theresantonie** [comment]
Thanks for the input @david-venhoff! Where can I find the changelog?

**Comment by JoeyStk** [comment]
> Thanks for the input @david-venhoff! Where can I find the changelog?

You can type `./tools/new_release_note.sh` and then give in the issue number and the language slug (either "de" or "en"), and as the third and last parameter you can leave an issue description :)

**Pull request merged**
