### PR TITLE
Use contenthash for css files

### PR DESCRIPTION
**Pull request by ulliholtgrave**
### Short description

This PR should fix the misbehavior of the cache dealing with CSS files. However, I am not completely sure if this affects all relevant CSS files. @timoludwig Can you verify this? :)

### Proposed changes

- Add contenthash to MiniCSSPlugin

### Resolved issues

Fixes: #1369

### CODE REVIEW

**Comment by ulliholtgrave** [comment]
Okay, There seems to be a problem with the PDF-Export... I'll look into it

**Comment by timoludwig** [comment]
> Okay, There seems to be a problem with the PDF-Export... I'll look into it

The css of the pdf should not be minified, because there was a bug with minified font face definitions (see https://github.com/xhtml2pdf/xhtml2pdf/pull/609)... my PR was merged, but no new version was released, so for the moment we have to keep excluding the pdf css from the minifier. Probably, we need change the `exclude: "pdf.css",` to a regex which contains a variable hash... (or we don't use the hash in the pdf because this is just internal for the pdf generation and never really cached by the browser.

**Comment by ulliholtgrave** [comment]
Okay, or we could just wait for the next release of XHTML2PDF and can merge this afterwards.

**Review by timoludwig — APPROVED** [review]
Thanks a lot, works as expected! :+1:
And yes, this handles all our css files:
- main.[hash].css
- editor_content.[hash].css
- editor.[hash].css (not generated at the moment because this module only contains js code)
- pdf.css (excluded from hash)

**Pull request merged**
