### PR TITLE
Fix #3063: Make save button consistent in organization form

### LINKED ISSUE #3063: Name save button consistent
### Motivation

We often name the button "Update" if an existing object is being edited and "Create/Publish" for a new one. Sucn differenciation is not implemented for the organization form currently. This is incocistent.

### Proposed Solution

Rename the button on the organization form depend on whether the object is being newly created or an existing one.

### Alternatives

Leave it as it is.

### PR DESCRIPTION
**Pull request by devhadvani**
### Short description

This PR updates the "Save" button in the organization form to display "Update" when editing an organization and "Create" when adding a new one for consistency across the CMS.

### Proposed changes

- Update organization form to show "Update" or "Create" based on whether the organization is new or being edited.

### Side effects

- No side effects

### Resolved issues

Fixes: #3063 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by JoeyStk — APPROVED** [review]
Thank you very much! LGTM!

**Review by theresantonie — APPROVED** [review]
LGTM!

**Comment by david-venhoff** [comment]
Please squash your changes before merging

**Comment by PeterNerlich** [comment]
@devhadvani Could you rebase, resolve the conflicts and squash everything into one single commit? Then we will merge your changes

**Comment by PeterNerlich** [comment]
@devhadvani  I notice that the tests related to translations still fail. As this is a common problem for us, but at the same time really not that critical and the file can just be regenerated in a clean form from the bits of existing translation and the reconciled source code, we make a script for that.

Try running `tools/resolve_translation_conflicts.sh` and manually squash your commits into a single one again. Thank you for your effort!

**Comment by PeterNerlich** [comment]
Oh no, I was just about to merge it, why did you close it? :rofl:

**Comment by PeterNerlich** [comment]
Or did you notice anything against merging this PR last minute? @devhadvani

**Comment by devhadvani** [comment]
no, i was just thinking to make new pr @PeterNerlich

**Comment by david-venhoff** [comment]
@PeterNerlich you forgot to squash

**Comment by PeterNerlich** [comment]
> no, i was just thinking to make new pr

I was surprised that I was able to reopen this PR just like that, I recently encountered the problem where this was not possible. Apparently it is allowed if the between repositories?

> you forgot to squash

Oh dang, I didn't look at the number of commits. We have a bit of a weird convention regarding that here – The convenient *Squash & Merge* button is disabled, we want only merge commits on develop so it does not end up being a separate history from any feature branch being merged. At the same time, we value a clean history with, for most PRs, only one commit. So we always manually rebase onto develop, squashing our commits down into a single one, and do so again when a script in the pipeline fails after all :sweat_smile: until we finally merge

**Pull request merged**
