### PR TITLE
Fix German translation of "Show more" in the MT overlay

### PR DESCRIPTION
**Pull request by JoeyStk**
### Short description

Fixes the bug in the German translation of "Show more" in the MT overlay. 

### Proposed changes

- Fix translation
- Add JS/TS test for `toggleOptionalText()`
- Introduce jsdom for more complex JS/TS tests

### Side effects

None I'm aware of

### Resolved issues

Fixes: #2830

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by JoeyStk** [comment]
@deen13 Do you have an idea why the imports in `eslint` are failing while they work locally and for `vitest`? :)

**Comment by deen13** [comment]
@JoeyStk Not really, but I'll look into it and post here as soon as I find something. :)

**Comment by JoeyStk** [comment]
It seems like the issues with eslint need some more time until they are resolved. Until then this PR is blocked :)

**Comment by deen13** [comment]
Performance issues have been resolved in #2847. Tomorrow, I will begin investigating the [invalid interface error](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/11764/workflows/058f1d10-fef0-4ac2-9944-8e1eb6b3b105/jobs/144497?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary&invite=true#step-103-458_105). :)

**Review by MizukiTemma — APPROVED** [review]
👍

**Review by deen13 — APPROVED** [review]
Good work 😎

**Pull request merged**
