### PR TITLE
Page revision timeline rework

### PR DESCRIPTION
**Pull request by deen13**
### Overview

This pull request re-implements the revision timeline feature. Originally targeting the issue described in #830, the project scope expanded to include a comprehensive refactor. The new implementation improves code readability and functionality by utilizing `flex-layout` and replacing `datalist` and `option` elements with click listeners for item selection.

In response to feedback from @osmers and @JoeyStk, the timeline has been made scrollable. Users can now navigate through the timeline using the previous and next buttons, the left and right arrow keys, or horizontal scrolling.

You can find a screencast that demonstrates the new behaviuor here: https://github.com/user-attachments/assets/418389df-3168-431f-a2c9-894acbdbb0b8.

### Key Changes

- Enhanced accessibility by increasing contrast for revision numbers.
- Improved layout by centering the timeline behind items for a more balanced and visually appealing design.
- Enhanced user interaction with an updated cursor to a pointer to indicate clickable items.
- Refined tooltips by adjusting positioning to ensure they consistently appear directly below the selected item.
- Fixed alignment issues to address any previous misplacement of items.
- Implemented fixed tooltip overflow management to ensure tooltips render on the left if they would exceed the container boundary.
- Enabled horizontal scrolling to accommodate numerous revisions without crowding.
- Added multiple navigation options for a comprehensive overview of the changes.

### Side Effects

- Scrolling Behavior: Scrolling events are only triggered when the content exceeds the container size. This means users cannot scroll through items if the timeline is not scrollable or is scrolled to the end.
- Feature Behavior Change: Users may notice changes in feature behavior. A tooltip introducing the new controls could be considered to assist those familiarizing themselves with the updated feature.

### Visual Comparison

**Before:**
Before Screenshot

**After:**
After Screenshot

### Related Issue

- Fixes: #830

---

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by osmers** [comment]
From what I've seen in the short video, I like it a lot :)

**Review by JoeyStk — COMMENTED** [review]
I didn't take the time to do a thorough review of the TS code yet. However from a first glance this looks very clean now. Thank you!

However when testing this, I was able to scroll vertically in Firefox, Chromium or Opera :/ When I clicked on the bullet, it didn't move the same way it does in the video. 
I'm unsure what the cause of this problem might be. Could it be [related to browsers?](https://caniuse.com/?search=vertical%20scroll)

**Comment by deen13** [comment]
Hey @JoeyStk, the browser compatibility looks good to me. How about we review it together during our co-working slot on Friday? 😊

**Comment by JoeyStk** [comment]
I had a look at this with @osmers and we are both very happy with the new implementation!
Currently we don't think it needs a popup or tooltip to explain this further, as we assume that this is self-explanatory enough. This might become necessary once more testing has been done, but for now this is good to go :rocket:

**Review by JoeyStk — APPROVED** [review]

**Review by lunars97 — APPROVED** [review]
Looks good now :+1:

**Comment by lunars97** [comment]
Maybe we need here a release note? :)

**Pull request merged**
