### PR TITLE
Improve handling of brandings

### PR DESCRIPTION
**Pull request by timobrembeck**
### Short description

This adds a few improvements to our whitelabel/branding functionality.

### Proposed changes

- ~Add possibility to set region-specific brandings~ (rejected, aschaffenburg is getting its own cms)
- Make radable branding title configurable
- Add more regions to the test data

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by timobrembeck** [comment]
> Add possibility to set region-specific brandings

I'm not sure however if this is a step in the right direction, if we're going to move hallo aschaffenburg to its own VM, then I'd remove this feature since there is no use case anymore.

The improvements to the readable title however still make sense in my opinion, especially with regard to #2391.

**Comment by svenseeberg** [comment]
> if we're going to move hallo aschaffenburg to its own VM, then I'd remove this feature since there is no use case anymore.

I think that moving them into their own server would work best. The maintenance effort for an additional server is quite low.

**Review by PeterNerlich — APPROVED** [review]
I've looked at the code changes and tried running the CMS with each possible `INTEGREAT_CMS_BRANDING` env value to observe the branding, and I have no complaints.

I'm only wondering whether it would be useful / reasonably easy to put the primary color in the `integreat_cms/core/settings.py` as well (currently it's in `integreat_cms/static/src/css/style.scss:76`+) – then it would all be in one place.

**Comment by timobrembeck** [comment]
> I'm only wondering whether it would be useful / reasonably easy to put the primary color in the `integreat_cms/core/settings.py` as well (currently it's in `integreat_cms/static/src/css/style.scss:76`+) – then it would all be in one place.

Hmm, I don't see an easy way to pass the settings from Python to CSS – also, the logos etc. reside in the static directory (which is where they belong), so I think keeping style information in the stylesheet makes sense here.

**Comment by timobrembeck** [comment]
> > if we're going to move hallo aschaffenburg to its own VM, then I'd remove this feature since there is no use case anymore.
> 
> I think that moving them into their own server would work best. The maintenance effort for an additional server is quite low. The bigger issue would be the migration itself. But we can configure a reverse proxy for all hello paths.

@svenseeberg Sounds good! Maybe a few redirects are sufficient until the app adjusts the new path and most devices are updated?

**Comment by timobrembeck** [comment]
Ok, I removed all code related to region-specific brandings, since there is no use case anymore if aschaffenburg is getting its own cms.

**Pull request merged**
