### PR TITLE
Fix error when granting additional page permissions

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

Fix error when granting additional page permissions

### Proposed changes

- Replace `user.regions` by `user.regions.all()`
- Add tests for page permissions

### Resolved issues

Fixes: #2284

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by svenseeberg — APPROVED** [review]
Thanks, looks good to me. AFAICT the tests do not cover the previous problem, but that is intended?

**Comment by timoludwig** [comment]
> Thanks, looks good to me. AFAICT the tests do not cover the previous problem, but that is intended?

Yes they do, since previously these tests would fail for the MANAGEMENT role? :thinking:

**Comment by svenseeberg** [comment]
> Yes they do, since previously these tests would fail for the MANAGEMENT role? thinking

Maybe something is wrong in my setup. When I remove the `.all()` the tests show no problem.

**Comment by timoludwig** [comment]
> Maybe something is wrong in my setup. When I remove the `.all()` the tests show no problem.

Ahh sorry you're right, because the views still return `200` and the error is just logged...
Damn, yeah then it's a bit more complicated to test this and requires some refactoring... Probably I will do this later so we can merge this PR (now?)

**Comment by timoludwig** [comment]
the broad except is the real problem here^^

**Comment by svenseeberg** [comment]
Thanks

**Pull request merged**
