### PR TITLE
Add search function for Media Library

### PR DESCRIPTION
**Pull request by MizukiTemma**
### Short description
The goal of this PR is to add  search funcionality for media library so users can look for directories and files that match key words.

So far keyword search of items is functioning, but the result is shown as Json string not properly displayed.

At the moment the chanes are applied only for admin media library but we can add the changes also to non-admin media library once everything is done.

I appreciate your help and advice!

### What already done

- Search box and button
- Search suggestion by ajax call
- Search for directories and media files that much the keyword

### What not yet functioning
- Display of searched items

### Resolved issues

Fixes: #931

### CODE REVIEW

**Comment by melegiul** [comment]
>The goal of this PR is to add search funcionality for media library so users can look for directories and files that match key words.
So far keyword search of items is functioning, but the result is shown as Json string not properly displayed.

Looks great to me so far, could you please make a rebase to the current develop branch followed by a clean install?
That would make it easier for us to step into your branch and help you, because the current develop branch has a different project structure

**Review by timoludwig — COMMENTED** [review]
@MizukiTemma @membralala I refactored the media library a bit to make the search functionality work:
- I added two different types of media library components: `DirectoryContentLibrary` for the "normal" view of directory content and `SearchResultLibrary` to view all search results for a given query.
- The preact router now extracts either the directory id or the search query from the url and renders the respective component
- The components either load the normal directory content or the search results, store the result in the state `mediaLibraryContent` and render the generic `Library` component.

Could you have a look at my changes and see if you think they make sense and if you have any suggestions for improvement? Please also tell if you don't understand something, then probably I should improve the documentation of the code.

**Review by timoludwig — APPROVED** [review]
From my perspective, this is ready to merge. :rocket: 
@MizukiTemma @membralala any objections?

**Comment by membralala** [comment]
Thanks for your support, @timoludwig, as far as I can see everything works flawless. Thanks also for the detailed comments!

**Pull request merged**
