### PR TITLE
Increase max URL length for linkchecker

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

Increase max URL length for linkchecker

### Proposed changes

- Increase the length from currently 255 characters to 1024

### Side effects

This results in a migration of the linkcheck app. Probably we need to manually execute
```
integreat-cms-cli makemigrations linkcheck && integreat-cms-cli migrate
```
on all our test & prod systems...

### Resolved issues

Part of: #1818

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by ulliholtgrave — APPROVED** [review]
Good catch, but wouldn't it be necessary to add a migration for all the linkcheck objects? Or do we want to adjust it on the production database?

**Comment by timoludwig** [comment]
> Good catch, but wouldn't it be necessary to add a migration for all the linkcheck objects? Or do we want to adjust it on the production database?

The problem is that we cannot add migrations for models which don't belong to our own app...
If I add a migration file for this, it tries to find the `Url` model in the `cms` app which obviously doesn't work... so unfortunately I see no other way than generating the migrations on the prod systems :cry:

**Comment by ulliholtgrave** [comment]
I see. Thanks for the explanation. I guess the PR is good to go then 👍

**Comment by svenseeberg** [comment]
But if we add a manual migration, would that not create issues for all future app releases?

**Comment by ulliholtgrave** [comment]
@svenseeberg I guess it won't be an issue as the linkcheck app is an separate app and after this PR it should generate new link URL objects with the newly defined field length

**Comment by svenseeberg** [comment]
But if the app releases an additional migration themselves, we would be required to run the migration merge command, don't we? Django will not be able to sort out the migration conflicts itself.

**Comment by timoludwig** [comment]
> But if we add a manual migration, would that not create issues for all future django-linkcheck app releases that include migrations themselves?

oh yes, you're right. This will generate conflicts which will be very cumbersome to fix :grimacing:

**Comment by ulliholtgrave** [comment]
Wouldn't it be better then to delete all the links and create the objects again with the new defined variable?

**Comment by svenseeberg** [comment]
> oh yes, you're right. This will generate conflicts which will be very cumbersome to fix grimacing

I think it would be okay to do this. We just need to make sure that the production CMS is not being killed by our state.highstate and an incomplete migration process. I'm not really sure how we can prevent this - we would have to check for new migrations in advance and throw errors?

**Comment by timoludwig** [comment]
> Wouldn't it be better then to delete all the links and create the objects again with the new defined variable?

The problems aren't the existing database objects (they are all smaller than the current max size), but the database schema.

**Comment by svenseeberg** [comment]
> we would have to check for new migrations in advance and throw errors?

I think we can add a pseudo state in our Salt config that uses https://docs.github.com/en/rest/repos/contents#get-repository-content to check for new migrations. We can keep track of fixed migrations in our Pillar?

**Comment by timoludwig** [comment]
Ok, I remembered that we did something similar with the auth app for the lunes project [a while ago](https://github.com/digitalfabrik/lunes-cms/commit/c6196980bd8fe5b6aac1796b393b1d3b3ab9a6bc#diff-32088c2d908f60a4bb90b97ebc7fa6dfc370c8142773975c4f609a31d0d5b680)... I guess the same workaround should do the trick here as well. Looks ugly but is probably a bit safer and less work than the check in salt.

**Comment by svenseeberg** [comment]
> Ok, I remembered that we did something similar with the auth app for the lunes project [a while ago](https://github.com/digitalfabrik/lunes-cms/commit/c6196980bd8fe5b6aac1796b393b1d3b3ab9a6bc#diff-32088c2d908f60a4bb90b97ebc7fa6dfc370c8142773975c4f609a31d0d5b680)... I guess the same workaround should do the trick here as well. Looks ugly but is probably a bit safer and less work than the check in salt.

I think that looks like a good solution :)

**Comment by ulliholtgrave** [comment]
I can't really test it with the current state of my local db, but I would trust you that this does the trick 👍 :)

**Comment by svenseeberg** [comment]
> I can't really test it with the current state of my local db, but I would trust you that this does the trick +1 :)

I tested the migration. It works. I did not, however, create a test setup with migrations within the linkcheck app.

**Pull request merged**
