### PR TITLE
Pin pip & setuptools version in `pyproject.toml`

### PR DESCRIPTION
**Pull request by timobrembeck**
### Short description

To avoid breaking changes in `setuptools`, I suggest to pin its version as well.
`pip` was just added because it came along with the new `--all` option, but I guess it only helps to make dev environments more stable and consistent, so I thought it wouldn't make sense to put in extra effort to filter out pip again.

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by PeterNerlich — APPROVED** [review]
Seems to work. Running `tools/update_dependencies.sh` gives me a bunch of bumped and reordered dependencies, but I guess that the latter might either be connected to ruff or another change inside pip freeze?

**Comment by timobrembeck** [comment]
> Seems to work. Running `tools/update_dependencies.sh` gives me a bunch of bumped and reordered dependencies, but I guess that the latter might either be connected to ruff or another change inside pip freeze?

Isn't the ordering always alphabetical?

I wanted to keep the PR small, so I only included the new packages without updating the rest of them.

**Comment by PeterNerlich** [comment]
> Isn't the ordering always alphabetical?

Yes, but it seems to be sorting case sensitive and handling dashes differently now.

<details><summary>I got this:</summary>

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 78f107c32..ddd1fada4 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -111,39 +111,44 @@ dev = [
     "types-requests",
 ]
 pinned = [
-    "aiohttp==3.9.3",
+    "Django==4.2.11",
+    "MarkupPy==1.14",
+    "PyPDF3==1.0.6",
+    "PyYAML==6.0.1",
+    "Pygments==2.17.2",
+    "aiohttp==3.9.5",
     "aiosignal==1.3.1",
     "annotated-types==0.6.0",
     "arabic-reshaper==3.0.0",
-    "argon2-cffi==23.1.0",
     "argon2-cffi-bindings==21.2.0",
-    "asgiref==3.7.2",
+    "argon2-cffi==23.1.0",
+    "asgiref==3.8.1",
     "asn1crypto==1.5.1",
     "asttokens==2.4.1",
     "attrs==23.2.0",
     "bcrypt==4.1.2",
-    "cbor2==5.6.1",
+    "cachetools==5.3.3",
+    "cbor2==5.6.3",
     "certifi==2024.2.2",
     "cffi==1.16.0",
     "charset-normalizer==3.3.2",
     "click==8.1.7",
-    "cryptography==42.0.2",
+    "cryptography==42.0.5",
     "cssselect2==0.7.0",
     "decorator==5.1.1",
     "deepl==1.17.0",
     "defusedxml==0.7.1",
     "diff-match-patch==20230430",
-    "Django==4.2.10",
     "django-cacheops==7.0.2",
     "django-cors-headers==4.3.1",
     "django-db-mutex==3.1.0",
     "django-debug-toolbar==4.3.0",
-    "django-import-export==3.3.7",
+    "django-import-export==3.3.8",
     "django-linkcheck==2.3.0",
     "django-polymorphic==3.1.0",
     "django-redis==5.4.0",
     "django-treebeard==4.7.1",
-    "django-webpack-loader==3.0.1",
+    "django-webpack-loader==3.1.0",
     "django-widget-tweaks==1.5.0",
     "et-xmlfile==1.1.0",
     "executing==2.0.1",
@@ -152,65 +157,72 @@ pinned = [
     "funcy==2.0",
     "geographiclib==2.0",
     "geopy==2.4.1",
-    "google-cloud-translate==3.15.0",
+    "google-api-core==2.18.0",
+    "google-auth==2.29.0",
+    "google-cloud-core==2.4.1",
+    "google-cloud-translate==3.15.3",
+    "googleapis-common-protos==1.63.0",
+    "grpcio-status==1.62.2",
+    "grpcio==1.62.2",
     "html5lib==1.1",
-    "idna==3.6",
-    "ipython==8.21.0",
+    "idna==3.7",
+    "ipython==8.23.0",
     "jedi==0.19.1",
-    "jsonschema==4.21.1",
     "jsonschema-specifications==2023.12.1",
-    "lxml==5.1.0",
-    "MarkupPy==1.14",
-    "matplotlib-inline==0.1.6",
+    "jsonschema==4.21.1",
+    "lxml==5.2.1",
+    "matplotlib-inline==0.1.7",
     "multidict==6.0.5",
     "natsort==8.4.0",
     "odfpy==1.4.1",
     "openpyxl==3.1.2",
     "oscrypto==1.3.0",
-    "parso==0.8.3",
+    "parso==0.8.4",
     "pexpect==4.9.0",
-    "pillow==10.2.0",
+    "pillow==10.3.0",
     "pip==24.0",
     "prompt-toolkit==3.0.43",
-    "psycopg==3.1.18",
+    "proto-plus==1.23.0",
+    "protobuf==4.25.3",
     "psycopg-binary==3.1.18",
+    "psycopg==3.1.18",
     "ptyprocess==0.7.0",
     "pure-eval==0.2.2",
-    "pycparser==2.21",
-    "pydantic==2.6.1",
-    "pydantic_core==2.16.2",
-    "Pygments==2.17.2",
-    "pyHanko==0.21.0",
+    "pyHanko==0.23.2",
+    "pyOpenSSL==24.1.0",
+    "pyasn1==0.6.0",
+    "pyasn1_modules==0.4.0",
+    "pycparser==2.22",
+    "pydantic==2.7.0",
+    "pydantic_core==2.18.1",
     "pyhanko-certvalidator==0.26.3",
-    "pyOpenSSL==24.0.0",
     "pyotp==2.9.0",
-    "PyPDF3==1.0.6",
     "pypng==0.20220715.0",
     "python-bidi==0.4.2",
-    "python-dateutil==2.8.2",
+    "python-dateutil==2.9.0.post0",
     "python-magic==0.4.27",
-    "PyYAML==6.0.1",
     "qrcode==7.4.2",
-    "redis==5.0.1",
-    "referencing==0.33.0",
+    "redis==5.0.3",
+    "referencing==0.34.0",
     "reportlab==3.6.13",
     "requests==2.31.0",
-    "rpds-py==0.17.1",
+    "rpds-py==0.18.0",
+    "rsa==4.9",
     "rules==3.3",
     "setuptools==65.5.0",
     "sgmllib3k==1.0.0",
     "six==1.16.0",
-    "sqlparse==0.4.4",
+    "sqlparse==0.5.0",
     "stack-data==0.6.3",
     "svglib==1.5.1",
     "tablib==3.5.0",
     "tinycss2==1.2.1",
-    "tqdm==4.66.1",
-    "traitlets==5.14.1",
-    "typing_extensions==4.9.0",
+    "tqdm==4.66.2",
+    "traitlets==5.14.3",
+    "typing_extensions==4.11.0",
     "tzlocal==5.2",
     "uritools==4.0.2",
-    "urllib3==2.2.0",
+    "urllib3==2.2.1",
     "wcwidth==0.2.13",
     "webauthn==1.11.1",
     "webencodings==0.5.1",
@@ -220,81 +232,87 @@ pinned = [
     "yarl==1.9.4",
 ]
 dev-pinned = [
-    "alabaster==0.7.16",
-    "astroid==3.0.3",
     "Babel==2.14.0",
-    "black==24.1.1",
-    "build==1.0.3",
+    "EditorConfig==0.12.4",
+    "Jinja2==3.1.3",
+    "MarkupSafe==2.1.5",
+    "PyJWT==2.8.0",
+    "SecretStorage==3.3.3",
+    "Sphinx==7.3.7",
+    "Werkzeug==3.0.2",
+    "alabaster==0.7.16",
+    "astroid==3.1.0",
+    "backports.tarfile==1.1.1",
+    "black==24.4.0",
+    "build==1.2.1",
     "bumpver==2023.1129",
     "cfgv==3.4.0",
     "colorama==0.4.6",
-    "coverage==7.4.1",
-    "cssbeautifier==1.14.11",
+    "coverage==7.4.4",
+    "cssbeautifier==1.15.1",
     "dill==0.3.8",
     "distlib==0.3.8",
     "djlint==1.34.1",
     "docutils==0.20.1",
-    "EditorConfig==0.12.3",
-    "execnet==2.0.2",
-    "filelock==3.13.1",
+    "execnet==2.1.1",
+    "filelock==3.13.4",
     "html-tag-names==0.1.2",
     "html-void-elements==0.1.0",
     "icdiff==2.0.7",
-    "identify==2.5.33",
+    "identify==2.5.36",
     "imagesize==1.4.1",
-    "importlib-metadata==7.0.1",
+    "importlib_metadata==7.1.0",
     "iniconfig==2.0.0",
     "isort==5.13.2",
-    "jaraco.classes==3.3.1",
+    "jaraco.classes==3.4.0",
+    "jaraco.context==5.3.0",
+    "jaraco.functools==4.0.1",
     "jeepney==0.8.0",
-    "Jinja2==3.1.3",
-    "jsbeautifier==1.14.11",
-    "json5==0.9.14",
-    "keyring==24.3.0",
+    "jsbeautifier==1.15.1",
+    "json5==0.9.25",
+    "keyring==25.1.0",
     "lexid==2021.1006",
     "looseversion==1.3.0",
     "markdown-it-py==3.0.0",
-    "MarkupSafe==2.1.5",
     "mccabe==0.7.0",
     "mdurl==0.1.2",
     "more-itertools==10.2.0",
-    "mypy==1.8.0",
     "mypy-extensions==1.0.0",
-    "nh3==0.2.15",
+    "mypy==1.9.0",
+    "nh3==0.2.17",
     "nodeenv==1.8.0",
-    "packaging==23.2",
+    "packaging==24.0",
     "pathspec==0.12.1",
-    "pkginfo==1.9.6",
+    "pkginfo==1.10.0",
     "platformdirs==4.2.0",
-    "pluggy==1.4.0",
+    "pluggy==1.5.0",
     "pprintpp==0.4.0",
-    "pre-commit==3.6.0",
-    "PyJWT==2.8.0",
-    "pylint==3.0.3",
+    "pre-commit==3.7.0",
     "pylint-django==2.5.5",
     "pylint-per-file-ignores==1.3.2",
     "pylint-plugin-utils==0.8.2",
+    "pylint==3.1.0",
     "pyproject_hooks==1.0.0",
-    "pytest==7.4.4",
     "pytest-circleci-parallelized==0.1.0",
-    "pytest-cov==4.1.0",
+    "pytest-cov==5.0.0",
     "pytest-django==4.8.0",
-    "pytest-httpserver==1.0.8",
     "pytest-icdiff==0.9",
-    "pytest-order==1.2.0",
+    "pytest-order==1.2.1",
     "pytest-testmon==1.4.5",
     "pytest-xdist==3.5.0",
-    "readme-renderer==42.0",
+    "pytest==7.4.4",
+    "pytest_httpserver==1.0.10",
+    "readme_renderer==43.0",
     "regex==2023.12.25",
-    "requests-mock==1.11.0",
+    "requests-mock==1.12.1",
     "requests-toolbelt==1.0.0",
     "rfc3986==2.0.0",
-    "rich==13.7.0",
-    "ruff==0.3.5",
-    "SecretStorage==3.3.3",
-    "shellcheck-py==0.9.0.6",
+    "rich==13.7.1",
+    "ruff==0.4.1",
+    "shellcheck-py==0.10.0.1",
     "snowballstemmer==2.2.0",
-    "Sphinx==7.2.6",
+    "sphinx-last-updated-by-git==0.3.6",
+    "sphinx-rtd-theme==2.0.0",
     "sphinxcontrib-applehelp==1.0.8",
     "sphinxcontrib-devhelp==1.0.6",
     "sphinxcontrib-django==2.5",
@@ -303,17 +321,14 @@ dev-pinned = [
     "sphinxcontrib-jsmath==1.0.1",
     "sphinxcontrib-qthelp==1.0.7",
     "sphinxcontrib-serializinghtml==1.1.10",
-    "sphinx-last-updated-by-git==0.3.6",
-    "sphinx-rtd-theme==2.0.0",
     "toml==0.10.2",
-    "tomlkit==0.12.3",
-    "twine==4.0.2",
-    "types-python-dateutil==2.8.19.20240106",
-    "types-PyYAML==6.0.12.12",
-    "types-requests==2.31.0.20240125",
-    "virtualenv==20.25.0",
-    "Werkzeug==3.0.1",
-    "zipp==3.17.0",
+    "tomlkit==0.12.4",
+    "twine==5.0.0",
+    "types-PyYAML==6.0.12.20240311",
+    "types-python-dateutil==2.9.0.20240316",
+    "types-requests==2.31.0.20240406",
+    "virtualenv==20.25.3",
+    "zipp==3.18.1",
 ]
 
 [project.urls]
```

</details>

**Comment by timobrembeck** [comment]
@PeterNerlich What does `sort --version` output on your machine?

**Comment by PeterNerlich** [comment]
```
$ sort --version
sort (GNU coreutils) 9.5
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Haertel and Paul Eggert.
```

**Comment by timobrembeck** [comment]
@PeterNerlich maybe it has to do with your environment, do you have the environment variable `LC_COLLATE` set to `C` by any chance?

**Comment by PeterNerlich** [comment]
> @PeterNerlich maybe it has to do with your environment, do you have the environment variable `LC_COLLATE` set to `C` by any chance?

Yes I do

**Comment by timobrembeck** [comment]
@PeterNerlich Then this behavior is expected, since this setting also influences the order of the `sort` command:

```
$ echo -e "c\nb\nB\na" | sort

a
b
B
c
```

```
$ echo -e "c\nb\nB\na" | LC_COLLATE=C sort

B
a
b
c
```

However, I guess we could manually unset this env var during the script to make the sorting agnostic of the user's locale.

**Comment by PeterNerlich** [comment]
Okay, running `LC_COLLATE="" tools/update_dependencies.sh` seems to only update a few dependencies without reordering. I wonder why I never noticed, I ran the tool at least once before. I also had `LC_COLLATE` set like that since the last time I installed my system (which was way before me being introduced to this project).

Does it make sense to set the env inside `tools/update_dependencies.sh` or `tools/_functions.sh`?

**Review by charludo — APPROVED** [review]
LGTM!

**Review by deen13 — APPROVED** [review]
Looks good to me plus I learned a lot about python package distribution 😄

**Pull request merged**
