### PR TITLE
Sync language grid width for table header and body

### PR DESCRIPTION
**Pull request by melegiul**
### Short description

Sync language grid width for table header and body

### Proposed changes

The problem is that despite both Element nodes (a-html-tags) in the header and in body of the the table have the same width of 18.67px, as inline-block elements they are followed whitespace Text nodes with different widths (4,08331px and 3,36664px)
So I updated the Elements node width so that both header and body have in total the exact same width of 22,0333px

Screenshot from 2021-12-08 15-33-03

### Resolved issues

Fixes: #1029

### CODE REVIEW

**Review by timoludwig — COMMENTED** [review]
Thanks a lot! :+1:
Feels kinda hacky, but if it works :smile: 
Could you add a small notice that this problem is now fixed to our [changelog](https://github.com/Integreat/integreat-cms/blob/develop/CHANGELOG.md)?

**Comment by melegiul** [comment]
Thank you for your review, yes it is hacky at the moment, because I did not found a proper way to sync the width of text node "whitespace". So far I tried by syncing parent nodes font-size, height, etc without success, but I will investigate this topic further in the future. I also updated now the changelog

**Review by timoludwig — COMMENTED** [review]
Thanks! :+1:
Sorry, I just noticed that it would be good to have the same change also for the events, POIs and push notification lists. Can you maybe add the same class in these lists as well?

**Comment by melegiul** [comment]
> Can you maybe add the same class in these lists as well?

Alright, I've now applied the changes to all other translatable content types

**Comment by melegiul** [comment]
But alternatively we could also go like this:
```
{% for language in languages %}<a href="..."><a/>{% endfor %}
```
Removing the line in front of the a tag and after the closing a tag would remove all these whitespace characters, which are harder to sync by css

**Review by timoludwig — APPROVED** [review]
> But alternatively we could also go like this:
> 
> ```
> {% for language in languages %}<a href="..."><a/>{% endfor %}
> ```
> 
> Removing the line break in front of the beginning a tag and after the closing a tag would remove all these whitespace characters, which are harder to sync by css

Oh, I like that idea! Maybe we could even use the `{% spaceless %}` template tag for this:
```
{% spaceless %}
    {% for language in languages %}
        <a href="..."><a/>
    {% endfor %}
{% endspaceless %}
```
But if you don't want to change it further, the current solution would also be fine for me.

**Comment by melegiul** [comment]
> Oh, I like that idea! Maybe we could even use the {% spaceless %} template tag for this:

I like the spaceless tag more, too. So I replced all whitespaces with a little fixed sized right margin, which syncs the elements width, too.

**Review by timoludwig — COMMENTED** [review]
Thanks, relly cool! :rocket: 

But I'm sorry, now I noticed another thing: The language flags are also used in the lists of archived pages and POIs... could you add the spaceless tag for these templates as well? :see_no_evil:

**Comment by melegiul** [comment]
> The language flags are also used in the lists of archived pages and POIs

Ok, I've added spaceless to archived pages, but in archived pois html this column seems not to exist. Is this intentional?

**Comment by timoludwig** [comment]
> Ok, I've added spaceless to archived pages, but in archived pois html this column seems not to exist. Is this intentional?

Sorry, my bad, I meant archived events.

**Review by timoludwig — APPROVED** [review]
Thanks a lot, I think that's it :rocket: :muscle:

**Pull request merged**
