### PR TITLE
Add vitest for frontend testing

### PR DESCRIPTION
**Pull request by deen13**
### Short Description

This pull request configures vitest and adds a simple test as suggested in my review of [deps/upgrade_webauthn_2_0](https://github.com/digitalfabrik/integreat-cms/pull/2716).

### Proposed Changes

- Added a test task to `package.json`
- Included required vitest dependency
- Implemented a simple test for URL and base64 encoding
- Configure vitest to ignore python dependencies
- Configure import/resolver to resolve imports correctly
- Add job to circleci workflow

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by JoeyStk — COMMENTED** [review]
Thank you a lot :rocket: I think this is a good step forward.

1. Small note: Once this PR is merged you can check the checkbox in our [meta issue for tests](https://github.com/digitalfabrik/integreat-cms/issues/765). 
2. I personally like vitest more than jest for our usecase. I think Jest has a lot of features that we don't need as we are web only and therefore I rather prefer the speed of vitest.
3. Lastly the reason why I don't approve yet. Do we need a dev tool for this? I'm kind of lost in the whole discussion about pre-commits and dev commands :confused: Once this question is answered I will approve this PR as it looks good to me so far :)

Special thanks for the dummy test. These things always help me to get started with a new feature :) In the mid-future we can remove it again, but for the beginning it's much appreciated (at least on my side) :)

**Comment by deen13** [comment]
@JoeyStk I've added a devtool and a pre-commit hook that calls it. ☺️

**Review by JoeyStk — APPROVED** [review]
I'm not an expert on this matter, but would like to move this forward.
To me this PR works. I didn't face issues when installing this and running the dev-tool. Thank you very much :)

**Comment by ulliholtgrave** [comment]
Thank you very much :+1: This really is an improvement! Could you squash the first two commits into one? Then, this is good to go :)

**Review by PeterNerlich — APPROVED** [review]

**Pull request merged**
