### PR TITLE
Add spoken languages icon to tinymce

### PR DESCRIPTION
**Pull request by JoeyStk**
### Short description

This PR adds the speech bubble icon to indicate spoken languages to the tinymce icon list and shortcuts.

### Proposed changes

- Add speech bubble to icon list
- Add shortcut for it

### Side effects

- I noticed one strange side effect when testing this. With the new icon we get a lot of unused white space underneath the icon option. However as I don't think it has anything to with my immediate changes and I also couldn't find any quick CSS fixes for it, I decided to leave it open for now. Does any of you have an idea how to fix this and could help me out? Thanks in advance!
grafik

### Resolved issues

Fixes: #2633 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by JoeyStk** [comment]
@seluianova Oh, thank you very much! I thought the issue was something completely different

**Review by MizukiTemma — APPROVED** [review]
Looks good 😸

**Review by seluianova — APPROVED** [review]
LGTM!

**UPD**.
Or you could even set it to 40x40.
_I suggested 80x80 because the previous icon (contact.svg) was 80x80, but it still had an unnecessary space at the bottom:_
image
40x40 IMO would look better.

**Comment by PeterNerlich** [comment]
> **UPD**. Or you could even set it to 40x40. _I suggested 80x80 because the previous icon (contact.svg) was 80x80, but it still had an unnecessary space at the bottom

Oh I finally got what you mean, probably! It's that the icon SVGs themselves have width/height html attributes, the last ones set to `80` each, despite the parent element being limited to 24px width and height with CSS. Somehow the width is squished to those 24px and the icon looks correct, but the height remains the same, invisibly sticks out over the borders of the popup items and pushes the boundaries of the popup itself.

image
I think we can remove the width and height html attributes from the SVGs, we might only need to check the viewBox – I noticed the light bulb icon and the one for opening hours are missing it and become weird when only removing width/height.

And while we're at it addressing cosmetics, we could also ensure the SVGs have a consistent look. I see that the light bulb has a fill set, the others have not, and it looks slightly different.

**Pull request merged**
