### PR TITLE
Change PDF library from xhtml2pdf to weasyprint

### PR DESCRIPTION
**Pull request by jonbulz**
### Short description
Replace xhtml2pdf by weasyprint, as there seem to be several formatting issues in pdfs generated with xhtml2pdf.

### Resolved Issues
I didn't get to do a lot of testing, but I believe #1499 and #1533 are better now.

### CODE REVIEW

**Comment by jonbulz** [comment]
I didn't check this as thoroughly as I would have liked, but I just wanted to open this PR now because I won't be free the next couple of days. This way, maybe somebody else can already have a look.

Oh, and obviously this requires the weasyprint module, which I just installed locally via pip. Would this need to be somewhere in this PR?

**Review by timobrembeck — COMMENTED** [review]
Thanks a lot! :+1:

In general, I approve the idea of moving towards a more stable PDF library, especially considering all the problems we had with xhtml2pdf in the past.

> I didn't get to do a lot of testing, but I believe #1499 and #1533 are better now.

Yes, this change seems to fix all of the weird PDF-bugs we have at the moment, also e.g. #1537! :+1:
I also did not have the time to do in-depth testing, but just from the first look, I already see a few points we need to address before making the change final.

- [ ] Fonts are not working yet (we should try to make the PDF look similar to the web app which includes using the same fonts for headings and the content)
- [ ] The table of contents is not working yet (all page titles aka `<h1>`-elements should be listed in the TOC)
- [ ] Images are not resized when they overlap the page
- [ ] The footer with page numbers and Integreat logo (and optionally the region logo) is missing


Probably, there are some more points I forgot, but we have to make sure that moving to another library does not re-open issues we already have fixed for xhtml2pdf.

> Oh, and obviously this requires the weasyprint module, which I just installed locally via pip. Would this need to be somewhere in this PR?

Adding functional dependencies is documented [here](https://digitalfabrik.github.io/integreat-cms/virtualenv.html#add-dependencies):

> When adding new functional dependencies, please add them to https://github.com/digitalfabrik/integreat-cms/blob/develop/setup.cfg and execute:
>
>     pipenv update integreat-cms

**Comment by jonbulz** [comment]
You're right, I didn't even notice. That doesn't look good at all. Unfortunately, wkhtmltopdf also doesn't seem to work right out of the box, so I guess it might be necessary to make some upstream contributions to one of the libraries to fix our issues.
I'll try to look into what would be the least effort to get where we want to. ^^

**Review by timobrembeck — CHANGES_REQUESTED** [review]
I'm just changing the status to make it easier to keep the overview which PRs still need reviews and which don't :wink:

**Comment by ulliholtgrave** [comment]
@jonbulz Thank you very much for your effort so far, but as we discussed in our last teamcall, we decided to fix our current setup with XHTML2PDF and maybe provide some upstream patches :+1: 

Therefore I am closing this PR for housekeeping :)

**Pull request closed without merging**
