### PR TITLE
Add API documentation

### PR DESCRIPTION
**Pull request by david-venhoff**
### Short description

This pr adds an api documentation.

### Proposed changes

- Add documentation to api/init.py

### Side effects

/

### Resolved issues

Fixes: #1690 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by svenseeberg** [comment]
Awesome, thanks! I'm wondering if we can establish a process that keeps the documentation and API in sync. I'm not sure how we can achieve this. Adding another check box to the pull request template is a bit mundane, right?

**Review by timoludwig — COMMENTED** [review]
> I'm wondering if we can establish a process that keeps the documentation and API in sync. I'm not sure how we can achieve this. Adding another check box to the pull request template is a bit mundane, right? If nobody has a good idea, I would approve this PR after having validated the endpoints.

I guess we could write a CircleCI check that fails when files in the API source code are changed without adapting the documentation :smile:
And the check is only bypassed when `[no-doc-change]` is present in the commit summary :grin: 
But probably an idea for another issue...

**Review by timoludwig — CHANGES_REQUESTED** [review]

**Review by timoludwig — APPROVED** [review]
:+1:

**Review by ulliholtgrave — APPROVED** [review]
Very nice! Thank you very much 😊

**Pull request merged**
