### PR TITLE
Add separate legend for statistics charts

### PR DESCRIPTION
**Pull request by charludo**
### Short description

Remove the legend at the top of the chart, replacing it with a box in the right-hand column, as shown in the [design proposal](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=1179-830) in preparation of #1097.

### Proposed changes

- remove old legend
- generate new legend server-side, using jinja
- wire them together using the method recommended in the [docs for chart.js](https://www.chartjs.org/docs/master/samples/legend/html.html)

### Side effects

- none

### Resolved issues

Fixes: #3133

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by JoeyStk — APPROVED** [review]
Wonderful! Thank you very much! Looks very good :)

**Review by lunars97 — COMMENTED** [review]
Thank you for this PR! :heart:  Everything looks good except this space on the screenshot below between the flag and the language name. I tested it on Chrome Version 130.0.6723.58 and Firefox version 124
image

**Comment by JoeyStk** [comment]
Ah, one other thing: Since this builds on an already existing feature and is going to be a change that municipalities might notice, a release note could make sense? @osmers What do you think? :)

**Comment by osmers** [comment]
@JoeyStk yes, I think a release note would make sense :)

**Comment by charludo** [comment]
> Ah, one other thing: Since this builds on an already existing feature and is going to be a change that municipalities might notice, a release note could make sense? @osmers What do you think? :)

Ah right, forgot to add it! Thanks!

**Review by lunars97 — APPROVED** [review]
Looks good now! :rocket:

**Review by JoeyStk — APPROVED** [review]
Wonderful! Thank you :)

**Pull request merged**
