### PR TITLE
Release `2022.5.3`

### PR DESCRIPTION
**Pull request by timoludwig**
### Short description

Now that we seem to be releasing on a daily basis, let's not make today an exception :wink:

### CHANGELOG

* [ [#1460](https://github.com/digitalfabrik/integreat-cms/issues/1460) ] Only show status in broken link checker for expert users
* [ [#742](https://github.com/digitalfabrik/integreat-cms/issues/742) ] Add default bounding box to region API
* [ [#1406](https://github.com/digitalfabrik/integreat-cms/issues/1406) ] Hide sub-headings in PDF table of contents

### CODE REVIEW

**Review by svenseeberg — DISMISSED** [review]
Please go ahead then :D

**Comment by timoludwig** [comment]
This seems to be blocked by https://github.com/digitalfabrik/integreat-app/pull/675

**Review by ulliholtgrave — DISMISSED** [review]
As I reviewed nearly all of the added commits, I guess this is good to go :+1:

**Review by ulliholtgrave — APPROVED** [review]
Still good to go :D

**Pull request merged**
