### PR TITLE
Replace icon for authority office / office

### PR DESCRIPTION
**Pull request by JoeyStk**
### Short description

Replace icon for authority office with a less negative icon

### Proposed changes

- Replace SVG file

### Side effects

None

### Resolved issues

Fixes: #2800

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by MizukiTemma — APPROVED** [review]
Maybe a release note? 😺

**Comment by ulliholtgrave** [comment]
Isn't this the common icon for museums? 🤔

**Comment by JoeyStk** [comment]
> Maybe a release note? 😺

Good point. I was torn as I was thinking that this is probably nothing the CMS users really notice, but they do (in the apps), right?

**Comment by MizukiTemma** [comment]
> > Maybe a release note? 😺
> 
> Good point. I was torn as I was thinking that this is probably nothing the CMS users really notice, but they do (in the apps), right?

Yes :)

**Review by timobrembeck — APPROVED** [review]

**Pull request merged**
