### PR TITLE
Do not show translation status of the root language

### PR DESCRIPTION
**Pull request by MizukiTemma**
### Short description

This is a revival of #2436 

- Do not show root language column in the event(page/poi list.
- Add a new flag for German (easy) to distinguish from German

### Resolved issues

Fixes: #2389 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by timobrembeck — COMMENTED** [review]
Probably, we need to update the library first to make use of the new flags, right?

**Comment by MizukiTemma** [comment]
@timobrembeck Thank you for the release in [flagpack-dart-sass](https://github.com/timobrembeck/flagpack-dart-sass) 👍

**Review by PeterNerlich — APPROVED** [review]
Seems to work perfectly

**Review by david-venhoff — CHANGES_REQUESTED** [review]
Looks good to me :tada: 

I only noticed that the changes don't apply to news yet (There the root language is still shown)

Also, somebody needs to make sure that we change the German (easy) flag once this pr lands in production

**Comment by MizukiTemma** [comment]
@david-venhoff nice catch 👀 The same changes are now applied for news and templates 😸

**Review by david-venhoff — COMMENTED** [review]
Oh, I found another problem :sweat_smile: 

We also show the translation status in the archived lists (archived pages, archived events, but not in archived pois for some reason)

I see two solutions here:
* Keep archived views as-is and also hide the root language there
* Remove the translation status indicator from archived views to make them more consistent with the archived poi list

**Comment by MizukiTemma** [comment]
@david-venhoff 
I'd go for the option 1 to keep everything out of the issue scope as is. An issue is opened to fix this inconsistency (#3071 )

**Review by david-venhoff — APPROVED** [review]
:tada:

**Pull request merged**
