### PR TITLE
Release `2024.11.1`

### PR DESCRIPTION
**Pull request by JoeyStk**
# Release notes

## unreleased

- [ [#3133](https://github.com/digitalfabrik/integreat-cms/issues/3133) ] Move the legend for statistics to its own box
- [ [#3150](https://github.com/digitalfabrik/integreat-cms/issues/3150) ] Fix spacing in poi box
- [ [#3183](https://github.com/digitalfabrik/integreat-cms/issues/3183) ] Fix error at bulk action link ignore and unignore
- [ [#3185](https://github.com/digitalfabrik/integreat-cms/issues/3185) ] Extend select all checkboxes to translation of events and pois

### CODE REVIEW

**Comment by JoeyStk** [comment]
Context for this release: we need the new commit for the region condition before the conference :)

**Comment by osmers** [comment]
It's also good bcs it fixes the 500 error for links, right? @JoeyStk

**Comment by JoeyStk** [comment]
Blocked by #3200

**Comment by MizukiTemma** [comment]
Shall we merge and deliver #3201 and #3202 too?

**Comment by JoeyStk** [comment]
> Shall we merge and deliver https://github.com/digitalfabrik/integreat-cms/pull/3201 and https://github.com/digitalfabrik/integreat-cms/pull/3202 too?

I spoke with @KateGithub12 and so long it's not urgent to merge them, I would like for Kate to have the privilege to merge the PRs next week :)

**Comment by juliankehne** [comment]
> @juliankehne The error with language node must be fixed now. Could you review again? 🙏

Once it's on cms-test I will. Right now it seems not there yet, still getting the error.

**Review by juliankehne — APPROVED** [review]
Tested the fix for region creation! LGTM

**Pull request merged**
