### PR TITLE
Add education icon to selection for location categories

### PR DESCRIPTION
**Pull request by timobrembeck**
### Short description

Add education icon to selection for location categories

### Proposed changes

- Add new icon
- Make icon available in selection for region categories

### Side effects

- Releasing this needs to be synced with the app

### Resolved issues

Fixes: #2262

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by MizukiTemma — APPROVED** [review]
LGTM 👍

**Review by JoeyStk — COMMENTED** [review]
Thank you! This looks very good.
I have one genuine question. I noticed, that we have 13 icons, but only twelve colors now. Is that a problem? Is there a need for one distinct color for every icon?

**Comment by timoludwig** [comment]
> I noticed, that we have 13 icons, but only twelve colors now. Is that a problem? Is there a need for one distinct color for every icon?

Yes, that's also what I mentioned in https://issues.tuerantuer.org/browse/KOMMUNE-569, and I think the service team would like to have an additional color, but they do not yet know which one...

**Review by seluianova — COMMENTED** [review]
I observe some problem with the resizing of the new icon.
Is it only on my laptop?
image
image

**Comment by timoludwig** [comment]
@seluianova ah, thanks for noticing! apparently, a `viewBox="0 0 40 40"` was missing... could you check again?

**Review by seluianova — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
