### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by timobrembeck**
### Short description

Update all dependencies

### Proposed changes

- Update pip dependencies
- Update npm dependencies

### Side effects

- Delayed update of `django-import-export` because of breaking changes

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by deen13** [comment]
Thanks for the work! I checked out the branch and was able to fetch all the new dependencies and start the server without any problems. However, committing code fails on my machine with the following error:

```bash
deen@mbp-3 integreat-cms % git commit -m "..."
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint.
An unexpected error has occurred: CalledProcessError: command: ('/Library/Developer/CommandLineTools/usr/libexec/git-core/git', 'checkout', 'v8.57.0')
return code: 1
stdout: (none)
stderr:
    error: pathspec 'v8.57.0' did not match any file(s) known to git
Check the log at /Users/deen/.cache/pre-commit/pre-commit.log
deen@mbp-3 integreat-cms % 
```

I tried running `pre-commit clean` and `pre-commit gc` to fix the problem, but that did not help.

**Review by deen13 — CHANGES_REQUESTED** [review]
Thanks for the work! I checked out the branch and was able to fetch all the new dependencies and start the server without any problems. However, committing code fails on my machine with the following error:

```bash
deen@mbp-3 integreat-cms % git commit -m "..."
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint.
An unexpected error has occurred: CalledProcessError: command: ('/Library/Developer/CommandLineTools/usr/libexec/git-core/git', 'checkout', 'v8.57.0')
return code: 1
stdout: (none)
stderr:
    error: pathspec 'v8.57.0' did not match any file(s) known to git
Check the log at /Users/deen/.cache/pre-commit/pre-commit.log
deen@mbp-3 integreat-cms % 
```

I tried running `pre-commit clean` and `pre-commit gc` to fix the problem, but that did not help.

**Comment by timobrembeck** [comment]
@deen13 ah right, I missed that the pre-commit repo apparently contains not all versions that are available on npm. Should be fixed now, could you check again?

**Review by deen13 — APPROVED** [review]
Yay it works 🥳

**Review by ulliholtgrave — APPROVED** [review]
Thanks, could update and install it. No issues found after some playing around :)

**Comment by ulliholtgrave** [comment]
But I guess we have to solve the conflicts that are probably related to the added vitest.

**Comment by timobrembeck** [comment]
I resolved the conflicts now. @deen13 @ulliholtgrave could one of you check again?

**Comment by ulliholtgrave** [comment]
Just reinstalled it and still seems to work :+1: However, I had to upgrade my node version in order to get rid of a lot of warnings. I'll write a notice to our internal chat :)

**Pull request merged**
