### PR TITLE
Release `2023.2.1`

### PR DESCRIPTION
**Pull request by ulliholtgrave**
### Changelog
* [ [#2056](https://github.com/digitalfabrik/integreat-cms/issues/2056) ] Change restriction of event duration to 28 days
* [ [#2032](https://github.com/digitalfabrik/integreat-cms/issues/2032) ] Remove gap between sidebar boxes in location form
* [ [#1989](https://github.com/digitalfabrik/integreat-cms/issues/1989) ] Improve load time of locations endpoint
* [ [#1578](https://github.com/digitalfabrik/integreat-cms/issues/1578) ] Add option to hide files in global media library
* [ [#1752](https://github.com/digitalfabrik/integreat-cms/issues/1752) ] Show chapter for internal link suggestions
* [ [#1965](https://github.com/digitalfabrik/integreat-cms/issues/1965) ] Add ical rrule for recurring events

### CODE REVIEW

**Review by svenseeberg — APPROVED** [review]
:rocket:

**Review by timoludwig — DISMISSED** [review]
Should we include #2082 in the release as well?

**Comment by ulliholtgrave** [comment]
I guess it's worth to wait for Sven's fix.@svenseeberg should I also provide a review?

**Comment by svenseeberg** [comment]
> I guess it's worth to wait for Sven's fix.@svenseeberg should I also provide a review?

I'll include Timos last comment in the next hours. If there's more, we should probably not wait?

**Comment by SteffiStuffel** [comment]
If this can be easily added to the release would be nice, as we can than start working on it in the frontend: https://github.com/digitalfabrik/integreat-cms/pull/2029

**Comment by ulliholtgrave** [comment]
> If this can be easily added to the release would be nice, as we can than start working on it in the frontend: #2029

@SteffiStuffel Your changes are already part of the release and i adjusted the PR description :)

**Comment by ulliholtgrave** [comment]
> > I guess it's worth to wait for Sven's fix.@svenseeberg should I also provide a review?
> 
> I'll include Timos last comment in the next hours. If there's more, we should probably not wait?

I agree, I propose that we release it this afternoon and if we are able to fix the remaining issues with the mutex we can include it. Otherwise, we'll bring that fix in a separate release.

**Pull request merged**
