### PR TITLE
Improve performance of the `fix_internal_links` management command

### PR DESCRIPTION
**Pull request by david-venhoff**
### Short description

This pr tries to improve the performance of the `fix_internal_links` management command.
I could not test it on production data, but I am hopeful that this can speed up the command a lot.

### Proposed changes

- Don't use the `replace_links` function and instead work directly on the already known translation (Also skips having to wait for linkcheck listeners + 0.1 seconds after each update)
- If a region is given, only include links of that region
- Make sure that not more than one new version per translation is created in the process

Also some minor improvements from reducing the number of database calls

### Side effects

Ideally none

### Resolved issues

Fixes: #2578

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Comment by david-venhoff** [comment]
Seems like this depends on #2648 to be merged

**Comment by ulliholtgrave** [comment]
After rebasing your commits, this seems good to go for me. I did some local testing with our page duplication and I noticed some performance improvements. As we don't really have additional ASAP fixes in our pipeline, I would vouch for merging this soon and test it on the test system.

**Review by MizukiTemma — APPROVED** [review]
Nice 🐱

**Review by ulliholtgrave — APPROVED** [review]
Thanks :+1:

**Pull request merged**
