### PR TITLE
Adapt offers API to web app

### PR DESCRIPTION
**Pull request by svenseeberg**
### Short description
The web app expects a null value instead of an empty dict in the offers API for the `post` attribute.

### Proposed changes
Convert the empty dict to null when delivering the information via API.

### CODE REVIEW

**Comment by svenseeberg** [comment]
We could add a test before merging :D

**Review by ulliholtgrave — APPROVED** [review]
I guess there should be some more elegant solutions, but I guess this is an emergency :+1:

**Comment by svenseeberg** [comment]
As I already fixed this in the production environment, we have the time to add a test case.

**Review by timoludwig — APPROVED** [review]
Thanks, works as expected! :+1:

I guess it would be a bit cleaner to put it into the `get_post_data()` function, but that's just personal preference...
```
if not post_data:
    return None
return post_data
```

**Comment by svenseeberg** [comment]
We have one additional bug: we need to replace `"search-plz":"{plz}"` with the actual zip code of each region.

**Comment by svenseeberg** [comment]
> We have one additional bug: we need to replace `"search-plz":"{plz}"` with the actual zip code of each region.

Oh wait, the code is already in there.

**Review by timoludwig — APPROVED** [review]
:+1:

**Comment by svenseeberg** [comment]
I guess we ignore the documentation build error (`intersphinx inventory 'https://docs.python-requests.org/en/master/objects.inv' not fetchable due to <class 'requests.exceptions.SSLError'>: HTTPSConnectionPool(host='docs.python-requests.org', port=443): Max retries exceeded with url: /en/master/objects.inv (Caused by SSLError(CertificateError("hostname 'docs.python-requests.org' doesn't match either of '*.ispapi.net', 'ispapi.net'")))`)?

**Comment by timoludwig** [comment]
> I guess we ignore the documentation build error

Last time we had this problem, we had weeks of failing builds until the documentation of pipenv was fixed... maybe we should temporarily remove the line
https://github.com/digitalfabrik/integreat-cms/blob/1b898ac34655530c734ef90ac08965ea45f1ac1d/sphinx/conf.py#L79
and add the few requests-references to the [nitpicky-ignore](https://github.com/digitalfabrik/integreat-cms/blob/1b898ac34655530c734ef90ac08965ea45f1ac1d/sphinx/conf.py#L129) setting?
But I don't know, could also only take hours until the certificate of the docs is fixed...

**Comment by svenseeberg** [comment]
It seems it was fixed while I added a line to the changelog ;-)

**Pull request merged**
