### PR TITLE
Add fields to POI form

### PR DESCRIPTION
**Pull request by JoeyStk**
### Short description
This PR adds the following three new sidebar boxes to the POI form.
- Stops in the vicinity
- Spoken languages
- Target group

### Proposed changes

For each one of these fields

- create according model
- add field to the form 
- add field to the API
- add according sidebar box

Maybe @osmers you can have a look at the screenshots below and decide if all requirements for each new field are met.
Stops in the vicinity:
grafik

Spoken languages: 
grafik

Target group:
grafik

### Side effects

- Dependent on how the spoken languages are being displayed inside the app it could be interesting to give the user a dropdown of all languages to help them select a language flag and language name 
- As @MizukiTemma already pointed out inside the issue description also here it could be interesting to add a dropdown button where the user can select from a list of pre-defined target groups

### Resolved issues

Fixes: Parts of #959

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by timobrembeck — CHANGES_REQUESTED** [review]
Thanks a lot! :+1:

I think in this case, it would have been better to clarify the existing questions before implementing the solution.

> Dependent on how the spoken languages are being displayed inside the app it could be interesting to give the user a dropdown of all languages to help them select a language flag and language name

Indeed, we already have a language model in our database - it would be stupid not to use it. Free text fields are always prone to error and do not help much when the fields should be used in the apps for filtering, because the same languages might be entered with slightly different spellings. A `forms.ModelMultipleChoiceField` with a `forms.CheckboxSelectMultiple` widget for example? Might need additional thoughts from UI/UX perspective.

> As @MizukiTemma already pointed out inside the issue description also here it could be interesting to add a dropdown button where the user can select from a list of pre-defined target groups

Completely agree, since this field probably is used as filter as well, it would be better to have a fixed set of possible choices here.

Apart from that, I question the free text field for "stops in the vicinity" - can't we use one of our location services to query the nearby stations automatically? Seems a lot of unnecessary effort for region managers to me.

But that's just my opinion, probably this needs further input to answer all open questions.

**Comment by osmers** [comment]
> Apart from that, I question the free text field for "stops in the vicinity" - can't we use one of our location services to query the nearby stations automatically? Seems a lot of unnecessary effort for region managers to me.

I completely agree - especially since they are already complaining that maintaining the POIs is too much work

**Comment by osmers** [comment]
Regarding the other two boxes planned - I think drop downs make a lot of sense - or maybe they can start typing a language and the correct selection comes up. That way they don't need to scroll through the whole list of languages :)

**Comment by MizukiTemma** [comment]
I think it's better to implement a possibility to create and manage target groups and their translations as we did for POI Category and Language.
Then it'll be easier to show and let users choose target groups and they are centrally managed and work well as filter.

**Comment by dkehne** [comment]
It might be useful that these three input-field (or 2 input-field if Haltestellen is generated automatically) are only maintable in expert-mode. As already mentioned it's at the moment already a lot of work to maintain the POIs and also if the argument is that you do not have to maintain the field, the municipalities often start with it, because it is possible and then they regret. 

Espacially because this is not derived from a need, but just a guess that this might be useful, we should not simply make it available for everyone.

**Comment by JoeyStk** [comment]
The requirements have been changed a lot and therefore this PR has become completely obsolete

**Pull request closed without merging**
