### PR TITLE
Deploy fixed region cloning, FCM messages, page form & translation status

### PR DESCRIPTION
**Pull request by svenseeberg**
* [ [#1086](https://github.com/digitalfabrik/integreat-cms/issues/1086) ] Provide correct URL for POI
* [ [#1247](https://github.com/digitalfabrik/integreat-cms/issues/1247) ] Update translation status on source status changes
* [ [#1251](https://github.com/digitalfabrik/integreat-cms/issues/1251) ] Fix change detection in page form
* [ [#1260](https://github.com/digitalfabrik/integreat-cms/issues/1260) ] Fix Firebase messaging
* [ [#1259](https://github.com/digitalfabrik/integreat-cms/issues/1259) ] Fix cloning of regions

### CODE REVIEW

**Review by timoludwig — DISMISSED** [review]

**Comment by timoludwig** [comment]
This is ready to deploy I think, we just have to keep in mind that it introduces one new bug (#1257) which should be fixed asap afterwards.

**Comment by svenseeberg** [comment]
This PR should wait for #1263

**Comment by svenseeberg** [comment]
We should merge #1263 and include it in this release.

**Comment by svenseeberg** [comment]
> This is ready to deploy I think, we just have to keep in mind that it introduces one new bug (#1257) which should be fixed asap afterwards.

I'll try to fix that later today. That means this PR can hopefully also wait for this.

**Review by timoludwig — APPROVED** [review]
:rocket:

**Pull request merged**
