### PR TITLE
Make machine translations always adopt the status of the source translation

### PR DESCRIPTION
**Pull request by PeterNerlich**
### Short description

Make machine translations always adopt the status of the source translation

### Proposed changes

- Remove code to use status of an existing translation in that language

### Side effects

- 

### Resolved issues

Fixes: #2549

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by david-venhoff — COMMENTED** [review]
Looks good to me. I think however that it would make sense to unify the status behavior across all translations, and currently summ ai always translates into `status.REVIEW`. Or is it intended that we have different behavior depending on which translation provider is used?

**Comment by osmers** [comment]
Uff, good catch - I think SUMM.AI translates into review bcs the municipalities need to (and can) correct the translations. That is something they cannot do with the foreign languages due to missing language skills. With SUMM.AI however, it is necessary bcs mostly the translation cannot be used as is.

**Review by david-venhoff — APPROVED** [review]
> With SUMM.AI however, it is necessary bcs mostly the translation cannot be used as is.

Alright, this looks good to me then

**Review by MizukiTemma — APPROVED** [review]
Looks good 👍 Thank you 😸

**Pull request merged**
