### PR TITLE
Fix spacing in poi box

### PR DESCRIPTION
**Pull request by JoeyStk**
### Short description

This PR attempts to fix the spacing issues in poi box.

### Proposed changes

- remove class `whitespace-pre-line`
- add `<br>` instead
- Avoid constructing the poi box client side. Instead, always render it on the server so that we don't have to maintain two versions of the same thing

### Side effects

I don't know

### Resolved issues

Fixes: #3150 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

### CODE REVIEW

**Review by david-venhoff — CHANGES_REQUESTED** [review]
Unfortunately this causes another problem, because we dynamically modify the contents of this div from js when a user selects a location: https://github.com/digitalfabrik/integreat-cms/blob/824cfad6f560f4983c048e7b55dcba743ec50b8e/integreat_cms/static/src/js/poi_box.ts#L36

You can see this if you create a new contact and select a location there for example. Since the assignment does not include the `<br>` tags, everything gets rendered in a single line now.

There are multiple solutions to this, for example
- Keep the `whitespace-pre-line` and build the address string in python. Then we could simply use something like this: `<div id="poi-address" class="text-lg whitespace-pre-line">{{ poi_address_text }}</div>`
- Keep the current solution and instead of assigning to text content in the js manually build html
- Completely get rid of the part where we build the address string in js and instead render everything on the server. Then `search_poi_ajax` would include the rendered poi addres div. That would also have the advantage that the layout cannot diverge anymore, as there is only a single place where it gets rendered

**Comment by JoeyStk** [comment]
@david-venhoff 
Oh, good catch. I went for option 2. Do you see any downsides with that? :)

**Review by david-venhoff — APPROVED** [review]
:grin:

**Review by MizukiTemma — APPROVED** [review]
Nice 😻 Thank you so much 👍 

We can probably add a release note, as this change is visible for users 👀 
And don't forget to squash the commits.

**Pull request merged**
